config/routes.rb
Rails.application.routes.draw do
  resources :wish_items
  get 'order_items/show'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index.html.erb"
  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resource :carts, only: [:show]
  # get 'carts/:id' => "carts#show", as: "cart"
  # delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :orders
  resources :addresses
  resources :claims
  resources :order_items

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders
    resources :claims
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :wish_items, dependent: :delete_all

  before_save :set_subtotal
  before_validation :set_default_status, on: :create

  enum status: {
    processing_order: 1,
    processing_error: 2,
    waiting_payment: 3,
    payment_accepted: 4,
    payment_denied: 5,
    finished: 6
  }


  include LocalizedEnumerable

  def subtotal
    wish_items.collect { |wish_item| wish_item.valid? ? (wish_item.unit_price * wish_item.quantity) : 0 }.sum
  end

  def payment_method
    if credit_card == true
      'Cartão de Crédito'
    elsif debit_card == true
      'Cartão de Debito'
    elsif billet == true
      'Boleto Bancário'
    elsif pix == true
      'PIX'
    end
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_default_status
    self.status = :processing_order
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  class OrdersController < BaseController
    before_action :set_order, only: %i[show edit update destroy]

    # GET /orders or /orders.json
    def index
      @orders = Order.all
    end

    # GET /orders/1 or /orders/1.json
    def show; end

    # GET /orders/new
    def new
      @order = Order.new
    end

    # GET /orders/1/edit
    def edit; end

    # POST /orders or /orders.json
    def create
      @order = Order.new(order_params)

      respond_to do |format|
        if @order.save
          format.html { redirect_to admin_order_url(@order), notice: "Pedido criado com sucesso!" }
          format.json { render :show, status: :created, location: @order }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /orders/1 or /orders/1.json
    def update
      respond_to do |format|
        if @order.update(order_params)
          format.html { redirect_to admin_order_url(@order), notice: "Pedido foi atualiado com sucesso." }
          format.json { render :show, status: :ok, location: @order }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /orders/1 or /orders/1.json
    def destroy
      @order.destroy

      respond_to do |format|
        format.html { redirect_to admin_orders_url, notice: "Pedido foi deletado com sucesso." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:first_name, :last_name, :email, :cpf, :phone, :cellphone, :street, :district, :number,
                                    :complement, :city, :state, :zip_number, :status, :subtotal, :total, :debit_card, :credit_card,
                                    :billet, :pix, :credit_card_number, :credit_card_name, :credit_card_expired_date,
                                    :credit_card_code, :wish_item_id)
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.save
    WishItem.all.each do |item|
      @order.update(wish_item_id: item.id)
    end
    if @order.save
      redirect_to orders_path, notice: 'Pedido criado com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_order_url(@order), notice: "Pedido foi atualiado com sucesso." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :cpf, :phone, :cellphone, :street, :district, :number,
                                  :complement, :city, :state, :zip_number, :status, :subtotal, :total, :debit_card, :credit_card,
                                  :billet, :pix, :credit_card_number, :credit_card_name, :credit_card_expired_date,
                                  :credit_card_code, :wish_item_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= simple_form_for([:admin, @order]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="loader"></div>
  <main id="main" role="main">
    <section id="checkout-container">
      <div class="container">
        <div class="py-5 text-center">
          <i class="fa fa-credit-card fa-3x text-primary"></i>
          <h2 class="my-3">Pedido</h2>
        </div>
        <div class="row py-5">
          <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
              <span class="text-muted">Seu carrinho</span>
            </h4>

            <ul class="list-group mb-3">
              <% WishItem.all.each do |wish_item| %>
                <li class="list-group-item d-flex justify-content-between lh-condensed">

                  <div>
                    <h6 class="my-0"><%= wish_item.product.name %></h6>
                    <small class="text-muted"><%= wish_item.product.description %></small>
                  </div>
                  <span class="text-muted"><%= number_to_currency(wish_item.product.price) %></span>

                </li>
              <% end %>
              <li class="list-group-item d-flex justify-content-between">
                <span>Total (R$)</span>
                <% price_total = WishItem.all.map{|item| item.product.price }.sum %>
                <strong><%= number_to_currency( price_total) %></strong>
              </li>
            </ul>
          </div>

          <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Endereço de Cobrança</h4>
            <form class="needs-validation" novalidate>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= f.input :first_name, class:"form-control", id:"firstName", placeholder:"", value:"" %>
                  <div class="invalid-feedback">
                    Valid first name is required.
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <%= f.input :last_name, class:"form-control", id:"lastName", placeholder:"", value:"" %>
                  <div class="invalid-feedback">
                    Valid last name is required.
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <%= f.input :email, type:"email", class:"form-control", id:"email", placeholder:"nome@exemplo.com" %>
                <div class="invalid-feedback">
                  Please enter a valid email address for shipping updates.
                </div>
              </div>

              <div class="mb-3">
                <%= f.input :status, class:"form-control", collection: Order.sorted_localized_statuses %>
                <div class="invalid-feedback">
                  Please enter a valid email address for shipping updates.
                </div>
              </div>

              <div class="row">
                <div class="col-md-4 mb-3">
                  <%= f.input :cpf, type:"cpf", class:"form-control", id:"cpf", placeholder:"000.000.000-00" %>
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>
                <div class="col-md-4 mb-3">
                  <%= f.input :cellphone, type:"cpf", class:"form-control", id:"cpf", placeholder:"(00) 00000-0000" %>
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>

                <div class="col-md-4 mb-3">
                  <%= f.input :phone, type:"cpf", class:"form-control", id:"cpf", placeholder:"(00) 0000-0000" %>
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>
              </div>



              <div class="mb-3">
                <%= f.input :street, class:"form-control", id:"address", placeholder:"" %>
                <div class="invalid-feedback">
                  Please enter your shipping address.
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= f.input :district, class:"form-control", id:"address", placeholder:"" %>
                </div>

                <div class="col-md-6 mb-3">
                  <%= f.input :number, class:"form-control", id:"address", placeholder:"1234" %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= f.input :city, class:"form-control", id:"address", placeholder:"" %>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <%= f.input :state, class:"form-control", id:"address", placeholder:"MS" %>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <%= f.input :zip_number, class:"form-control", id:"zip", placeholder:"00.000-000" %>
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>
              <hr class="mb-4">
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Savar estas informações para pedidos futuros</label>
              </div>
              <hr class="mb-4">

              <h4 class="mb-3">Pagamento</h4>

              <div class="d-block my-3">
                <div class="custom-control custom-radio">
                  <%= f.input :debit_card, id:"credit", name:"paymentMethod", type:"radio", class:"custom-control-input" %>
                </div>
                <div class="custom-control custom-radio">
                  <%= f.input :credit_card, id:"credit", name:"paymentMethod", type:"radio", class:"custom-control-input" %>
                </div>
                <div class="custom-control custom-radio">
                  <%= f.input :billet, id:"credit", name:"paymentMethod", type:"radio", class:"custom-control-input" %>
                </div>
                <div class="custom-control custom-radio">
                  <%= f.input :pix, id:"credit", name:"paymentMethod", type:"radio", class:"custom-control-input" %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= f.input :credit_card_name, type:"text", class:"form-control", id:"cc-name", placeholder:""  %>
                  <small class="text-muted">Nome completo impresso no cartão</small>
                  <div class="invalid-feedback">
                    Name on card is required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <%= f.input :credit_card_number, type:"text", class:"form-control", id:"cc-number", placeholder:"" %>
                  <div class="invalid-feedback">
                    Credit card number is required
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <%= f.input :credit_card_expired_date, type:"text", class:"form-control", id:"cc-expiration", placeholder:"" %>
                  <div class="invalid-feedback">
                    Expiration date required
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <%= f.input :credit_card_code, class:"form-control", id:"cc-cvv",  placeholder:"" %>
                  <div class="invalid-feedback">
                    Security code required
                  </div>
                </div>
              </div>
              <hr class="mb-4">
              <%= f.button :submit, 'Atualizar pedido', class: 'btn btn-primary btn-lg btn-block' %>
            </form>
          </div>
        </div>
      </div>
    </section>
  </main>
<% end %>

app/views/admin/orders/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button
            type="button"
              class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                style="background: none; border: none;">
          x
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/orders/form", order: @order %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Status:</strong>
    <%= Order.human_attribute_name("status.#{order.status}") %>
  </p>
  <p>
    <strong>Tipo de pagamento:</strong>
    <%= order.credit_card %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= order.email %>
  </p>
  <% WishItem.all.each do |wish_item| %>
    <p>
      <strong>Nome do Produto:</strong>
      <%= wish_item.product.name %>
    </p>
    <p>
      <strong>Preço:</strong>
      <%= wish_item.product.price %>
    </p>
  <% end %>
  <p>
    <strong>Total:</strong>
    <% price_total = WishItem.all.map{|item| item.product.price }.sum %>
    <%= number_to_currency( price_total) %>
  </p>

  <p>
    <strong>Usuário:</strong>
    <%= order.first_name %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= order.street %>
  </p>

</div>

app/views/admin/orders/edit.html.erb
<h1>Editar pedido</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", order: @order %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/orders/form_modal", locals: { order: @order }%>
<% end %>

app/views/admin/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Pedidos</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
          <th>Usuário</th>
          <th>Status</th>
          <th>Email</th>
          <th>Total</th>
          <th>Tipo de Pagamento</th>
          <th>Endereço</th>
          <th>Cidade</th>
          <th>Estado</th>
          <th>Ações</th>
          </thead>
          <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.first_name %></td>
              <td><%= Order.human_attribute_name("status.#{order.status}") %></td>
              <td><%= order.email %></td>
              <% price_total = WishItem.all.map{|item| item.product.price }.sum %>
              <td><%= number_to_currency( price_total) %></td>
              <td><%= order.payment_method %></td>
              <td><%= order.street %></td>
              <td><%= order.city %></td>
              <td><%= order.state %></td>
              <td>
                <%= link_to "Detalhes", admin_order_path(order), class: 'btn btn-dark' %>
                <%= link_to "Editar", edit_admin_order_path(order), data: { controller: 'admin-modal' }, class: 'btn btn-warning' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Voltar para pedidos", admin_orders_path %>
</div>

app/views/admin/orders/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/orders/form_modal", locals: { order: @order }%>
<% end %>

app/views/admin/orders/show.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="h3 mb-4 text-gray-800">Detalhes do Pedido</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @order %>
      </div>
    </div>
  </div>
</div>