config/routes.rb
Rails.application.routes.draw do
  resources :wish_items
  get 'order_items/show'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index.html.erb"
  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resource :carts, only: [:show]
  # get 'carts/:id' => "carts#show", as: "cart"
  # delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :orders
  resources :addresses
  resources :claims
  resources :order_items

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders
    resources :claims
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  # association
  # --
  belongs_to :user

  # validation
  # --
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  # association
  # --
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :wish_items, dependent: :delete_all

  before_save :set_subtotal
  before_validation :set_default_status, on: :create

  enum status: {
    processing_order: 1,
    processing_error: 2,
    waiting_payment: 3,
    payment_accepted: 4,
    payment_denied: 5,
    finished: 6
  }


  include LocalizedEnumerable

  def subtotal
    wish_items.collect { |wish_item| wish_item.valid? ? (wish_item.unit_price * wish_item.quantity) : 0 }.sum
  end

  def payment_method
    if credit_card == true
      'Cartão de Crédito'
    elsif debit_card == true
      'Cartão de Debito'
    elsif billet == true
      'Boleto Bancário'
    elsif pix == true
      'PIX'
    end
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_default_status
    self.status = :processing_order
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :small_thumb, resize_to_limit: [300, 300]
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end
  belongs_to :category

  validates :name, :description, :price, presence: true

  def total
    products = Product.all

    products.each(&:price).sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  has_one_attached :avatar

  has_many :addresses
  has_many :claims
  has_many :wish_items
  has_many :orders

  enum role: { user: 0, admin: 1 }
end

app/models/wish_item.rb
class WishItem < ApplicationRecord
  belongs_to :product
  belongs_to :user


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.map { |product| ProductPresenter.new(product) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?
    'profile'
  end
end

app/helpers/wish_items_helper.rb
module WishItemsHelper
end

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
      <div class="copyright text-center my-auto">
      </div>
  </div>
</footer>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

	<a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_root_path %>">
		<div class="sidebar-brand-icon rotate-n-15">
			<i class="fas fa-laugh-wink"></i>
		</div>
		<div class="sidebar-brand-text mx-3">ADMINSOlIDARIO</div>
	</a>

	<hr class="sidebar-divider my-0">

	<li class="nav-item active">
		<a class="nav-link" href="<%= admin_root_path %>">
			<i class="fas fa-fw fa-tachometer-alt"></i>
			<span>Dashboard</span>
		</a>
	</li>

	<hr class="sidebar-divider">

	<li class="nav-item">
		<a class="nav-link collapsed" href="<%= admin_orders_path %>">
			<i class="fas fa-store"></i>
			<span>Pedidos</span>
		</a>
	</li>

	<li class="nav-item">
		<a class="nav-link collapsed" href="<%= admin_categories_path %>">
			<i class="fas fa-layer-group"></i>
			<span>Categorias</span>
		</a>
	</li>

	<li class="nav-item">
		<a class="nav-link collapsed" href="<%= admin_products_path %>">
			<i class="fas fa-puzzle-piece"></i>
			<span>Produtos</span>
		</a>
	</li>

	<li class="nav-item">
		<a class="nav-link collapsed" href="<%= admin_claims_path %>">
			<i class="fas fa-exclamation"></i>
			<span>Dúvidas e Reclamações</span>
		</a>
	</li>

	<li class="nav-item">
		<a class="nav-link collapsed" data-method="delete" href="<%= destroy_user_session_path %>">
			<i class="fas fa-arrow-alt-circle-left"></i>
			<span>Sair</span>
		</a>
	</li>

	<hr class="sidebar-divider d-none d-md-block">

	<div class="text-center d-none d-md-inline">
		<button class="rounded-circle border-0" id="sidebarToggle"></button>
	</div>

</ul>

app/views/layouts/admin/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
              <%= image_tag 'undraw_profile.svg', class: 'img-profile rounded-circle' %>
          </a>
          <!-- Dropdown - User Information -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
              aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
              </a>
              <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
              </a>
              <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
              </a>
          </div>
      </li>

  </ul>

</nav>

app/views/layouts/shared/_flash.html.erb
<div class="alert alert-info text-center">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/store/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white"> &copy; Ecommerce Solidário 2023</p></div>
</footer>

app/views/layouts/store/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="#!">Loja Virtual</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item"><a class="nav-link" aria-current="page" href="<%= root_path %>">Home</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="<%= orders_path %>">Meus Pedidos</a></li>
            <%= render 'layouts/store/user_signed_in' %>
          </ul>
          <div class="d-flex">
            <a class="btn btn-outline-dark" type="submit" href="<%= wish_items_path %>">
              <i class="bi-cart-fill me-1"></i>
              Carrinho
              <span class="badge bg-dark text-white ms-1 rounded-pill"><%= WishItem.present? ? WishItem.all.count : '0'  %></span>
            </a>
          </div>
      </div>
  </div>
</nav>

app/views/layouts/store/_user_signed_in.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to "Meu Perfil", settings_path, class: "nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link"  %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Cadastre-se", new_user_registration_path, method: :delete, class: "nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Entrar", new_user_session_path, method: :delete, class: "nav-link"  %>
  </li>
<% end %>