config/routes.rb
Rails.application.routes.draw do
  resources :wish_items
  get 'order_items/show'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index.html.erb"
  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resource :carts, only: [:show]
  # get 'carts/:id' => "carts#show", as: "cart"
  # delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :orders
  resources :addresses
  resources :claims
  resources :order_items

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders
    resources :claims
  end
end

app/models/wish_item.rb
class WishItem < ApplicationRecord
  belongs_to :product
  belongs_to :user


end

app/controllers/wish_items_controller.rb
class WishItemsController < ApplicationController
  before_action :set_wish_item, only: %i[ show edit update destroy ]

  # GET /wish_items or /wish_items.json
  def index
    @wish_items = WishItem.all
  end

  # GET /wish_items/1 or /wish_items/1.json
  def show
  end

  # GET /wish_items/new
  def new
    @wish_item = WishItem.new
  end

  # GET /wish_items/1/edit
  def edit
  end

  # POST /wish_items or /wish_items.json
  def create
    @wish_item = current_user.wish_items.build(product_id: params[:product_id])
    respond_to do |format|
      if @wish_item.save
        format.html { redirect_to root_path, notice: "Adicionado ao carrinho com sucesso!" }
        format.json { render :show, status: :created, location: @wish_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wish_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wish_items/1 or /wish_items/1.json
  def update
    respond_to do |format|
      if @wish_item.update(wish_item_params)
        format.html { redirect_to wish_item_url(@wish_item), notice: "Wish item was successfully updated." }
        format.json { render :show, status: :ok, location: @wish_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wish_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wish_items/1 or /wish_items/1.json
  def destroy
    @wish_item = current_user.wish_items.find(params[:id])

    respond_to do |format|
      @wish_item.destroy!
      format.html { redirect_to wish_items_url, notice: "Wish item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish_item
      @wish_item = WishItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wish_item_params
      params.require(:wish_item).permit(:product_id)
    end
end

app/helpers/wish_items_helper.rb
module WishItemsHelper
end

app/views/wish_items/_form.html.erb
<%= simple_form_for(@wish_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :product %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wish_items/_wish_item.html.erb
<div id="<%= dom_id wish_item %>">
  <p>
    <strong>Product:</strong>
    <%= wish_item.product_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= wish_item.user_id %>
  </p>

</div>

app/views/wish_items/edit.html.erb
<h1>Editing wish item</h1>

<%= render "form", wish_item: @wish_item %>

<br>

<div>
  <%= link_to "Show this wish item", @wish_item %> |
  <%= link_to "Back to wish items", wish_items_path %>
</div>

app/views/wish_items/index.html.erb
<h1>Carrinho de Compras</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Produtos</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Subtotal</th>
            <th>Ação</th>

          </thead>
          <tbody>
          <% @wish_items.each do |wish_item| %>
            <tr>
              <td>
                <div class="product-image">
                  <%#= image_tag wish_item.product.image.variant(:small_thumb), class: 'card-img-top' if wish_item.product.image.present? %>
                </div>
                <div class="product-name">
                  <%= wish_item.product.name %>
                </div>

              </td>
              <td><%= number_to_currency(wish_item.product.price) %></td>
              <td><%= '1' %></td>
              <td><%= number_to_currency(wish_item.product.price) %></td>
              <td><%= link_to "x", wish_item_path(wish_item), method: :delete, class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Deseja realmente exlcuir?'} %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
          <%= link_to "Prosseguir para Checkout", new_order_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wish_items/new.html.erb
<h1>New wish item</h1>

<%= render "form", wish_item: @wish_item %>

<br>

<div>
  <%= link_to "Back to wish items", wish_items_path %>
</div>

app/views/wish_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wish_item %>

<div>
  <%= link_to "Edit this wish item", edit_wish_item_path(@wish_item) %> |
  <%= link_to "Back to wish items", wish_items_path %>

  <%= button_to "Destroy this wish item", @wish_item, method: :delete %>
</div>