config/routes.rb
Rails.application.routes.draw do
  resources :wish_items
  get 'order_items/show'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index.html.erb"
  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resource :carts, only: [:show]
  # get 'carts/:id' => "carts#show", as: "cart"
  # delete 'carts/:id' => "carts#destroy"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :orders
  resources :addresses
  resources :claims
  resources :order_items

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
    resources :orders
    resources :claims
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  # association
  # --
  belongs_to :user

  # validation
  # --
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  # association
  # --
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :wish_items, dependent: :delete_all

  before_save :set_subtotal
  before_validation :set_default_status, on: :create

  enum status: {
    processing_order: 1,
    processing_error: 2,
    waiting_payment: 3,
    payment_accepted: 4,
    payment_denied: 5,
    finished: 6
  }


  include LocalizedEnumerable

  def subtotal
    wish_items.collect { |wish_item| wish_item.valid? ? (wish_item.unit_price * wish_item.quantity) : 0 }.sum
  end

  def payment_method
    if credit_card == true
      'Cartão de Crédito'
    elsif debit_card == true
      'Cartão de Debito'
    elsif billet == true
      'Boleto Bancário'
    elsif pix == true
      'PIX'
    end
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_default_status
    self.status = :processing_order
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :small_thumb, resize_to_limit: [300, 300]
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end
  belongs_to :category

  validates :name, :description, :price, presence: true

  def total
    products = Product.all

    products.each(&:price).sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  has_one_attached :avatar

  has_many :addresses
  has_many :claims
  has_many :wish_items
  has_many :orders

  enum role: { user: 0, admin: 1 }
end

app/models/wish_item.rb
class WishItem < ApplicationRecord
  belongs_to :product
  belongs_to :user


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.map { |product| ProductPresenter.new(product) }
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def password; end

  def update_user
    if current_user.update(user_params)
      redirect_to settings_path, notice: 'Seus dados foram atualizado com sucesso.'
    else
      render :index
    end
  end

  def update_password
    # TODO: Refatorar esse algoritmo
    if !current_password_params[:current_password].empty? && current_user.valid_password?(current_password_params[:current_password])
      if current_user.update(password_params)
        bypass_sign_in(current_user)
        redirect_to password_settings_path, notice: 'Sua senha foi atualizada com sucesso.'
      else
        render :password
      end
    else
      redirect_to password_settings_path, notice: 'Você precisa informar sua senha atual para trocar de senha'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :avatar)
  end

  def current_password_params
    params.require(:user).permit(:current_password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?
    'profile'
  end
end

app/helpers/wish_items_helper.rb
module WishItemsHelper
end

app/views/settings/_menu.html.erb
<ul class="list-group list-group-flush">
  <a href="<%= settings_path %>" class="menu-item-profile"><li class="list-group-item">Meu perfil</li></a>
  <a href="<%= password_settings_path %>" class="menu-item-profile"><li class="list-group-item">Alterar senha</li></a>
  <a href="<%= addresses_path %>" class="menu-item-profile"><li class="list-group-item">Endereços</li></a>
  <a href="<%= claims_path %>" class="menu-item-profile"><li class="list-group-item">Dúvidas e Reclamações</li></a>
</ul>

app/views/settings/index.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2><%= current_user.name %></h2>
            <%= image_tag user_avatar_url(current_user), width: 120, height: 120, class: 'mb-4 rounded-circle' %>
            <%= simple_form_for current_user, url: update_user_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :avatar, label: false, hint: 'Escolha uma foto para sua conta.', input_html: { class: 'input_image_full' } %>
              <%= f.input :email, readonly: true %>
              <%= f.input :name %>
              <%= f.input :phone, input_html: { class: 'mask-phone' } %>
              <%= f.button :submit, "Atualizar", class: 'btn btn-primary mt-4' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/settings/password.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2>Alterar senha</h2>
            <%= simple_form_for current_user, url: update_password_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :current_password %>
              <%= f.input :password %>
              <%= f.input :password_confirmation %>
              <%= f.button :submit, "Atualizar senha", class: 'btn btn-primary mt-4' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>